# -*- coding: utf-8 -*-
"""image_captioning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NcXB_06sJsNtK7RptE1hOWXGEFKjDpum
"""

# pip install transformers torch Pillow requests
from transformers import BlipProcessor, BlipForConditionalGeneration
from PIL import Image
import requests

def generate_caption(image_path):
    print("Loading state-of-the-art BLIP model...")
    # Load pre-trained processor and model from Hugging Face
    processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
    model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

    # Load image from URL or local path
    if image_path.startswith("http"):
        image = Image.open(requests.get(image_path, stream=True).raw).convert('RGB')
    else:
        image = Image.open(image_path).convert('RGB')

    print("Processing image and generating caption...")
    # Process image and generate caption
    inputs = processor(image, return_tensors="pt")
    out = model.generate(**inputs, max_new_tokens=50)
    caption = processor.decode(out[0], skip_special_tokens=True)

    return caption

if __name__ == "__main__":
    print("--- Image Captioning AI ---")
    print("Using Salesforce BLIP model for state-of-the-art captioning.\n")

    # You can provide a local image path (e.g., 'my_photo.jpg') or a URL
    image_url = "https://images.unsplash.com/photo-1517849845537-4d257902454a?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80"

    caption = generate_caption(image_url)
    print(f"\nGenerated Caption: '{caption}'")

from google.colab import files
import os

# Upload an image file
uploaded = files.upload()

for filename in uploaded.keys():
    print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')
    # Optionally save the file locally if needed, though generate_caption can handle the path directly
    with open(filename, 'wb') as f:
        f.write(uploaded[filename])

    local_path = filename
    print(f"Processing local file: {local_path}")
    local_caption = generate_caption(local_path)
    print(f"\nGenerated Caption for '{local_path}': '{local_caption}'")