# -*- coding: utf-8 -*-
"""movie_recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbN4sFngUSoFA3aeAna621mi0DY-bkNA
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

# Creating a sample dataset for demonstration.
data = {
    'title': ['The Matrix', 'The Dark Knight', 'Inception', 'Interstellar', 'The Godfather',
              'Pulp Fiction', 'Forrest Gump', 'The Shawshank Redemption', 'Fight Club', 'The Prestige'],
    'tags': [
        'sci-fi action cyberpunk dystopia artificial intelligence',
        'action crime superhero thriller dark knight',
        'sci-fi action thriller dream heist subconscious',
        'sci-fi adventure space travel wormhole relativity',
        'crime drama mafia family classic',
        'crime drama dark comedy hitman',
        'drama romance historical comedy inspiring',
        'drama prison hope friendship classic',
        'drama thriller psychological underground fighting',
        'thriller drama mystery magic illusion'
    ]
}

df = pd.DataFrame(data)

# Convert tags into numerical vectors using TF-IDF
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['tags'])

# Compute the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

def get_recommendations(title, cosine_sim=cosine_sim, df=df):
    # Create a mapping of lowercase titles to indices
    indices = pd.Series(df.index, index=df['title'].str.lower()).drop_duplicates()

    # Get the index of the movie that matches the title (case-insensitive)
    idx = indices[title.lower()]

    # Get the pairwise similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 3 most similar movies (index 0 is the movie itself)
    sim_scores = sim_scores[1:4]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    return df['title'].iloc[movie_indices]

if __name__ == "__main__":
    print("--- Movie Recommendation System ---")
    print("Available movies:", ", ".join(df['title']))
    movie_name = input("\nEnter a movie you like: ")

    # Check if the movie exists (case-insensitive)
    if movie_name.lower() in df['title'].str.lower().values:
        recommendations = get_recommendations(movie_name)
        print(f"\nTop 3 recommendations based on '{movie_name}':")
        for i, movie in enumerate(recommendations, 1):
            print(f"{i}. {movie}")
    else:
        print("Movie not found in the database.")