# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ohYOzhXGIq4FhukBAbyMapXCpqrqLbr
"""

import re
import random
import datetime

def chatbot():
    # Define rules using regex patterns
    rules = {
        r'\b(hello|hi|hey|good morning|good evening)\b': [
            "Hello there! How can I assist you today?",
            "Hi! Hope you're having a great day.",
            "Hey! What's on your mind?"
        ],
        r'\bhow are you\b': [
            "I'm just a bunch of code, but I'm functioning perfectly!",
            "Doing great, thanks for asking! How are you?"
        ],
        r'\btime\b': [
            f"The current time is {datetime.datetime.now().strftime('%H:%M:%S')}.",
        ],
        r'\bdate\b': [
            f"Today's date is {datetime.datetime.now().strftime('%Y-%m-%d')}.",
        ],
        r'\bthank(s| you)\b': [
            "You're very welcome!",
            "Anytime! Happy to help."
        ],
        r'\bbye|goodbye|see you\b': [
            "Goodbye! Have a wonderful day ahead.",
            "See you later! Take care."
        ],
        r'\bwho created you\b|your name': [
            "I am the CODSOFT AI Bot, created for this internship task!",
            "You can call me CodBot."
        ]
    }

    print("--- Welcome to the Rule-Based Chatbot ---")
    print("Type 'quit' or 'exit' to end the chat.\n")

    while True:
        user_input = input("You: ").lower()

        if user_input in ['quit', 'exit']:
            print("Bot: Goodbye! It was nice chatting with you.")
            break

        matched = False
        # Check user input against the regex rules
        for pattern, responses in rules.items():
            if re.search(pattern, user_input):
                print("Bot:", random.choice(responses))
                matched = True
                break

        # Fallback response if no pattern matches
        if not matched:
            print("Bot: I'm sorry, I didn't quite catch that. Could you rephrase?")

if __name__ == "__main__":
    chatbot()